In [14]:
import numpy as np

In [11]:
list1 = list(range(11))

list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
new_list = []
for item in list1:
    new_list.append(item +5)

print(new_list)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [15]:
arr = np.array(list1)
print(arr + 5)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [23]:
integers = list(range(1,16))
print(integers)
arr2 = np.array(integers)
print(arr2 ** 2)
type(arr2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


numpy.ndarray

In [33]:
new_arr = np.array([[1,2,3,4.,5], [1,2,3,4,5]])

new_arr

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [34]:
print(new_arr.shape)
print(new_arr.size)
print(new_arr.dtype)

(2, 5)
10
float64


In [38]:
np.zeros((2,3))
np.ones((2,3))
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
print(list(range(0,11,2)))

[0, 2, 4, 6, 8, 10]


In [ ]:
print(np.arange(0,11,3))

[ 0  2  4  6  8 10]


In [43]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [55]:
access_arr = np.arange(0,11)
print(access_arr)
print(access_arr[2 : 6])
print(access_arr[2 : ])
print(access_arr[ : 5])

[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4 5]
[ 2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]


In [78]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr_2d)

# print(arr_2d[0,1])
# print(arr_2d[0][1])

print(arr_2d[ : , 0])
print(arr_2d[1, :])


[[1 2 3]
 [4 5 6]]
[1 4]
[4 5 6]


In [85]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# merge
print(np.concat((a,b)))
# matrix addition
print(a  + b)
# matrix multiplication
print(a * b)
a.shape

[1 2 3 4 5 6]
[5 7 9]
[ 4 10 18]


(3,)

In [88]:
numbers = np.array([10,20,30,40,50])
print(numbers.mean())
print(numbers.sum())
print(numbers.min())
print(numbers.max())


30.0
150
10
50


In [92]:
ushaped = np.arange(1,10)
print(ushaped)
print(ushaped.reshape((3,3)))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
ex1 = np.array([3,2,9])
ex2 = np.array([1,2,3])
print(ex1 + ex2)
print(np.dot(ex1,ex2))
print(np.dot(ex2,ex1))

[ 4  4 12]
34
34


In [ ]:
array_unfiltered = np.array([10,20,30,40,50,60,70])

print(array_unfiltered > 31)

filtered = array_unfiltered[array_unfiltered > 31]
print(filtered)

[False False False  True  True  True  True]
[40 50 60 70]


In [144]:
import random
import math

print(math.floor(1 + random.random() * 100))

95
